const theiaThemeExample = {
  "--theia-foreground": "#616161",
  "--theia-disabledForeground": "rgba(97, 97, 97, 0.5)",
  "--theia-errorForeground": "#a1260d",
  "--theia-descriptionForeground": "#717171",
  "--theia-icon-foreground": "#424242",
  "--theia-focusBorder": "#0090f1",
  "--theia-selection-background": "#c0dbf1",
  "--theia-textSeparator-foreground": "rgba(0, 0, 0, 0.18)",
  "--theia-textLink-foreground": "#006ab1",
  "--theia-textLink-activeForeground": "#006ab1",
  "--theia-textPreformat-foreground": "#a31515",
  "--theia-textBlockQuote-background": "rgba(127, 127, 127, 0.1)",
  "--theia-textBlockQuote-border": "rgba(0, 122, 204, 0.5)",
  "--theia-textCodeBlock-background": "rgba(220, 220, 220, 0.4)",
  "--theia-widget-shadow": "rgba(0, 0, 0, 0.16)",
  "--theia-input-background": "#18181b",
  "--theia-input-foreground": "#616161",
  "--theia-inputOption-activeBorder": "#007acc",
  "--theia-inputOption-hoverBackground": "rgba(184, 184, 184, 0.31)",
  "--theia-inputOption-activeBackground": "rgba(0, 144, 241, 0.2)",
  "--theia-inputOption-activeForeground": "#000000",
  "--theia-input-placeholderForeground": "#767676",
  "--theia-inputValidation-infoBackground": "#d6ecf2",
  "--theia-inputValidation-infoBorder": "#007acc",
  "--theia-inputValidation-warningBackground": "#f6f5d2",
  "--theia-inputValidation-warningBorder": "#b89500",
  "--theia-inputValidation-errorBackground": "#f2dede",
  "--theia-inputValidation-errorBorder": "#be1100",
  "--theia-dropdown-background": "#18181b",
  "--theia-dropdown-foreground": "#616161",
  "--theia-dropdown-border": "#cecece",
  "--theia-button-foreground": "#18181b",
  "--theia-button-separator": "rgba(255, 255, 255, 0.4)",
  "--theia-button-background": "#007acc",
  "--theia-button-hoverBackground": "#0062a3",
  "--theia-button-secondaryForeground": "#18181b",
  "--theia-button-secondaryBackground": "#5f6a79",
  "--theia-button-secondaryHoverBackground": "#4c5561",
  "--theia-badge-background": "#c4c4c4",
  "--theia-badge-foreground": "#333333",
  "--theia-scrollbar-shadow": "#dddddd",
  "--theia-scrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
  "--theia-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--theia-scrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
  "--theia-progressBar-background": "#0e70c0",
  "--theia-editorError-foreground": "#e51400",
  "--theia-editorWarning-foreground": "#bf8803",
  "--theia-editorInfo-foreground": "#1a85ff",
  "--theia-editorHint-foreground": "#6c6c6c",
  "--theia-sash-hoverBorder": "#0090f1",
  "--theia-editor-background": "#18181b",
  "--theia-editor-foreground": "#000000",
  "--theia-editorStickyScroll-background": "#18181b",
  "--theia-editorStickyScrollHover-background": "#f0f0f0",
  "--theia-editorWidget-background": "#18181b",
  "--theia-editorWidget-foreground": "#18181b",
  "--theia-editorWidget-border": "rgb(250 250 250 / 0.1)",
  "--theia-quickInput-background": "#f3f3f3",
  "--theia-quickInput-foreground": "#616161",
  "--theia-quickInputTitle-background": "rgba(0, 0, 0, 0.06)",
  "--theia-pickerGroup-foreground": "#0066bf",
  "--theia-pickerGroup-border": "#cccedb",
  "--theia-keybindingLabel-background": "rgba(221, 221, 221, 0.4)",
  "--theia-keybindingLabel-foreground": "#555555",
  "--theia-keybindingLabel-border": "rgba(204, 204, 204, 0.4)",
  "--theia-keybindingLabel-bottomBorder": "rgba(187, 187, 187, 0.4)",
  "--theia-editor-selectionBackground": "#add6ff",
  "--theia-editor-inactiveSelectionBackground": "#e5ebf1",
  "--theia-editor-selectionHighlightBackground": "rgba(173, 214, 255, 0.5)",
  "--theia-editor-findMatchBackground": "#a8ac94",
  "--theia-editor-findMatchHighlightBackground": "rgba(234, 92, 0, 0.33)",
  "--theia-editor-findRangeHighlightBackground": "rgba(180, 180, 180, 0.3)",
  "--theia-searchEditor-findMatchBackground": "rgba(234, 92, 0, 0.22)",
  "--theia-search-resultsInfoForeground": "#616161",
  "--theia-editor-hoverHighlightBackground": "rgba(173, 214, 255, 0.15)",
  "--theia-editorHoverWidget-background": "#f3f3f3",
  "--theia-editorHoverWidget-foreground": "#616161",
  "--theia-editorHoverWidget-border": "#c8c8c8",
  "--theia-editorHoverWidget-statusBarBackground": "#e7e7e7",
  "--theia-editorLink-activeForeground": "#0000ff",
  "--theia-editorInlayHint-foreground": "#969696",
  "--theia-editorInlayHint-background": "rgba(196, 196, 196, 0.1)",
  "--theia-editorInlayHint-typeForeground": "#969696",
  "--theia-editorInlayHint-typeBackground": "rgba(196, 196, 196, 0.1)",
  "--theia-editorInlayHint-parameterForeground": "#969696",
  "--theia-editorInlayHint-parameterBackground": "rgba(196, 196, 196, 0.1)",
  "--theia-editorLightBulb-foreground": "#ddb100",
  "--theia-editorLightBulbAutoFix-foreground": "#007acc",
  "--theia-diffEditor-insertedTextBackground": "rgba(156, 204, 44, 0.25)",
  "--theia-diffEditor-removedTextBackground": "rgba(255, 0, 0, 0.2)",
  "--theia-diffEditor-insertedLineBackground": "rgba(155, 185, 85, 0.2)",
  "--theia-diffEditor-removedLineBackground": "rgba(255, 0, 0, 0.2)",
  "--theia-main-content-panel": "#18181b",
  "--theia-diffEditor-diagonalFill": "rgba(34, 34, 34, 0.2)",
  "--theia-diffEditor-unchangedRegionBackground": "#e4e4e4",
  "--theia-diffEditor-unchangedRegionForeground": "#4d4c4c",
  "--theia-diffEditor-unchangedCodeBackground": "rgba(184, 184, 184, 0.16)",
  "--theia-list-focusOutline": "#0090f1",
  "--theia-list-activeSelectionBackground": "#0060c0",
  "--theia-list-activeSelectionForeground": "#18181b",
  "--theia-list-activeSelectionIconForeground": "#18181b",
  "--theia-list-inactiveSelectionBackground": "#e4e6f1",
  "--theia-list-hoverBackground": "#e8e8e8",
  "--theia-list-dropBackground": "#d6ebff",
  "--theia-list-highlightForeground": "#0066bf",
  "--theia-list-focusHighlightForeground": "#bbe7ff",
  "--theia-list-invalidItemForeground": "#b89500",
  "--theia-list-errorForeground": "#b01011",
  "--theia-list-warningForeground": "#855f00",
  "--theia-listFilterWidget-background": "#f3f3f3",
  "--theia-listFilterWidget-outline": "rgba(0, 0, 0, 0)",
  "--theia-listFilterWidget-noMatchesOutline": "#be1100",
  "--theia-listFilterWidget-shadow": "rgba(0, 0, 0, 0.16)",
  "--theia-list-filterMatchBackground": "rgba(234, 92, 0, 0.33)",
  "--theia-tree-indentGuidesStroke": "#a9a9a9",
  "--theia-tree-inactiveIndentGuidesStroke": "rgba(169, 169, 169, 0.4)",
  "--theia-tree-tableColumnsBorder": "rgba(97, 97, 97, 0.13)",
  "--theia-tree-tableOddRowsBackground": "rgba(97, 97, 97, 0.04)",
  "--theia-list-deemphasizedForeground": "#8e8e90",
  "--theia-checkbox-background": "#18181b",
  "--theia-checkbox-selectBackground": "#f3f3f3",
  "--theia-checkbox-foreground": "#616161",
  "--theia-checkbox-border": "#cecece",
  "--theia-checkbox-selectBorder": "#424242",
  "--theia-quickInputList-focusForeground": "#18181b",
  "--theia-quickInputList-focusIconForeground": "#18181b",
  "--theia-quickInputList-focusBackground": "#0060c0",
  "--theia-menu-foreground": "#616161",
  "--theia-menu-background": "#18181b",
  "--theia-menu-selectionForeground": "#18181b",
  "--theia-menu-selectionBackground": "#0060c0",
  "--theia-menu-separatorBackground": "#d4d4d4",
  "--theia-toolbar-hoverBackground": "rgba(184, 184, 184, 0.31)",
  "--theia-toolbar-activeBackground": "rgba(166, 166, 166, 0.31)",
  "--theia-editor-snippetTabstopHighlightBackground": "rgba(10, 50, 100, 0.2)",
  "--theia-editor-snippetFinalTabstopHighlightBorder": "rgba(10, 50, 100, 0.5)",
  "--theia-breadcrumb-foreground": "rgba(97, 97, 97, 0.8)",
  "--theia-breadcrumb-background": "#18181b",
  "--theia-breadcrumb-focusForeground": "#4e4e4e",
  "--theia-breadcrumb-activeSelectionForeground": "#4e4e4e",
  "--theia-breadcrumbPicker-background": "#f3f3f3",
  "--theia-merge-currentHeaderBackground": "rgba(64, 200, 174, 0.5)",
  "--theia-merge-currentContentBackground": "rgba(64, 200, 174, 0.2)",
  "--theia-merge-incomingHeaderBackground": "rgba(64, 166, 255, 0.5)",
  "--theia-merge-incomingContentBackground": "rgba(64, 166, 255, 0.2)",
  "--theia-merge-commonHeaderBackground": "rgba(96, 96, 96, 0.4)",
  "--theia-merge-commonContentBackground": "rgba(96, 96, 96, 0.16)",
  "--theia-editorOverviewRuler-currentContentForeground":
    "rgba(64, 200, 174, 0.5)",
  "--theia-editorOverviewRuler-incomingContentForeground":
    "rgba(64, 166, 255, 0.5)",
  "--theia-editorOverviewRuler-commonContentForeground":
    "rgba(96, 96, 96, 0.4)",
  "--theia-editorOverviewRuler-findMatchForeground": "rgba(209, 134, 22, 0.49)",
  "--theia-editorOverviewRuler-selectionHighlightForeground":
    "rgba(160, 160, 160, 0.8)",
  "--theia-minimap-findMatchHighlight": "#d18616",
  "--theia-minimap-selectionOccurrenceHighlight": "#c9c9c9",
  "--theia-minimap-selectionHighlight": "#add6ff",
  "--theia-minimap-infoHighlight": "#1a85ff",
  "--theia-minimap-warningHighlight": "#bf8803",
  "--theia-minimap-errorHighlight": "rgba(255, 18, 18, 0.7)",
  "--theia-minimap-foregroundOpacity": "#000000",
  "--theia-minimapSlider-background": "rgba(100, 100, 100, 0.2)",
  "--theia-minimapSlider-hoverBackground": "rgba(100, 100, 100, 0.35)",
  "--theia-minimapSlider-activeBackground": "rgba(0, 0, 0, 0.3)",
  "--theia-problemsErrorIcon-foreground": "#e51400",
  "--theia-problemsWarningIcon-foreground": "#bf8803",
  "--theia-problemsInfoIcon-foreground": "#1a85ff",
  "--theia-charts-foreground": "#616161",
  "--theia-charts-lines": "rgba(97, 97, 97, 0.5)",
  "--theia-charts-red": "#e51400",
  "--theia-charts-blue": "#1a85ff",
  "--theia-charts-yellow": "#bf8803",
  "--theia-charts-orange": "#d18616",
  "--theia-charts-green": "#388a34",
  "--theia-charts-purple": "#652d90",
  "--theia-editor-lineHighlightBorder": "#eeeeee",
  "--theia-editor-rangeHighlightBackground": "rgba(253, 255, 0, 0.2)",
  "--theia-editor-symbolHighlightBackground": "rgba(234, 92, 0, 0.33)",
  "--theia-editorCursor-foreground": "#000000",
  "--theia-editorWhitespace-foreground": "rgba(51, 51, 51, 0.2)",
  "--theia-editorLineNumber-foreground": "#237893",
  "--theia-editorIndentGuide-background": "#d3d3d3",
  "--theia-editorIndentGuide-activeBackground": "#939393",
  "--theia-editorIndentGuide-background1": "#d3d3d3",
  "--theia-editorIndentGuide-background2": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-background3": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-background4": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-background5": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-background6": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-activeBackground1": "#939393",
  "--theia-editorIndentGuide-activeBackground2": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-activeBackground3": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-activeBackground4": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-activeBackground5": "rgba(0, 0, 0, 0)",
  "--theia-editorIndentGuide-activeBackground6": "rgba(0, 0, 0, 0)",
  "--theia-editorActiveLineNumber-foreground": "#0b216f",
  "--theia-editorLineNumber-activeForeground": "#0b216f",
  "--theia-editorRuler-foreground": "#d3d3d3",
  "--theia-editorCodeLens-foreground": "#919191",
  "--theia-editorBracketMatch-background": "rgba(0, 100, 0, 0.1)",
  "--theia-editorBracketMatch-border": "#b9b9b9",
  "--theia-editorOverviewRuler-border": "rgba(127, 127, 127, 0.3)",
  "--theia-editorGutter-background": "#18181b",
  "--theia-editorUnnecessaryCode-opacity": "rgba(0, 0, 0, 0.47)",
  "--theia-editorGhostText-foreground": "rgba(0, 0, 0, 0.47)",
  "--theia-editorOverviewRuler-rangeHighlightForeground":
    "rgba(0, 122, 204, 0.6)",
  "--theia-editorOverviewRuler-errorForeground": "rgba(255, 18, 18, 0.7)",
  "--theia-editorOverviewRuler-warningForeground": "#bf8803",
  "--theia-editorOverviewRuler-infoForeground": "#1a85ff",
  "--theia-editorBracketHighlight-foreground1": "#0431fa",
  "--theia-editorBracketHighlight-foreground2": "#319331",
  "--theia-editorBracketHighlight-foreground3": "#7b3814",
  "--theia-editorBracketHighlight-foreground4": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketHighlight-foreground5": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketHighlight-foreground6": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketHighlight-unexpectedBracket-foreground":
    "rgba(255, 18, 18, 0.8)",
  "--theia-editorBracketPairGuide-background1": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-background2": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-background3": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-background4": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-background5": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-background6": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground1": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground2": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground3": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground4": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground5": "rgba(0, 0, 0, 0)",
  "--theia-editorBracketPairGuide-activeBackground6": "rgba(0, 0, 0, 0)",
  "--theia-editorUnicodeHighlight-border": "#cea33d",
  "--theia-editorUnicodeHighlight-background": "rgba(206, 163, 61, 0.08)",
  "--theia-diffEditor-move-border": "rgba(139, 139, 139, 0.61)",
  "--theia-diffEditor-moveActive-border": "#ffa500",
  "--theia-editorOverviewRuler-bracketMatchForeground": "#a0a0a0",
  "--theia-symbolIcon-arrayForeground": "#616161",
  "--theia-symbolIcon-booleanForeground": "#616161",
  "--theia-symbolIcon-classForeground": "#d67e00",
  "--theia-symbolIcon-colorForeground": "#616161",
  "--theia-symbolIcon-constantForeground": "#616161",
  "--theia-symbolIcon-constructorForeground": "#652d90",
  "--theia-symbolIcon-enumeratorForeground": "#d67e00",
  "--theia-symbolIcon-enumeratorMemberForeground": "#007acc",
  "--theia-symbolIcon-eventForeground": "#d67e00",
  "--theia-symbolIcon-fieldForeground": "#007acc",
  "--theia-symbolIcon-fileForeground": "#616161",
  "--theia-symbolIcon-folderForeground": "#616161",
  "--theia-symbolIcon-functionForeground": "#652d90",
  "--theia-symbolIcon-interfaceForeground": "#007acc",
  "--theia-symbolIcon-keyForeground": "#616161",
  "--theia-symbolIcon-keywordForeground": "#616161",
  "--theia-symbolIcon-methodForeground": "#652d90",
  "--theia-symbolIcon-moduleForeground": "#616161",
  "--theia-symbolIcon-namespaceForeground": "#616161",
  "--theia-symbolIcon-nullForeground": "#616161",
  "--theia-symbolIcon-numberForeground": "#616161",
  "--theia-symbolIcon-objectForeground": "#616161",
  "--theia-symbolIcon-operatorForeground": "#616161",
  "--theia-symbolIcon-packageForeground": "#616161",
  "--theia-symbolIcon-propertyForeground": "#616161",
  "--theia-symbolIcon-referenceForeground": "#616161",
  "--theia-symbolIcon-snippetForeground": "#616161",
  "--theia-symbolIcon-stringForeground": "#616161",
  "--theia-symbolIcon-structForeground": "#616161",
  "--theia-symbolIcon-textForeground": "#616161",
  "--theia-symbolIcon-typeParameterForeground": "#616161",
  "--theia-symbolIcon-unitForeground": "#616161",
  "--theia-symbolIcon-variableForeground": "#007acc",
  "--theia-actionBar-toggledBackground": "rgba(0, 144, 241, 0.2)",
  "--theia-peekViewTitle-background": "#f3f3f3",
  "--theia-peekViewTitleLabel-foreground": "#000000",
  "--theia-peekViewTitleDescription-foreground": "#616161",
  "--theia-peekView-border": "#1a85ff",
  "--theia-peekViewResult-background": "#f3f3f3",
  "--theia-peekViewResult-lineForeground": "#646465",
  "--theia-peekViewResult-fileForeground": "#1e1e1e",
  "--theia-peekViewResult-selectionBackground": "rgba(51, 153, 255, 0.2)",
  "--theia-peekViewResult-selectionForeground": "#6c6c6c",
  "--theia-peekViewEditor-background": "#f2f8fc",
  "--theia-peekViewEditorGutter-background": "#f2f8fc",
  "--theia-peekViewEditorStickyScroll-background": "#f2f8fc",
  "--theia-peekViewResult-matchHighlightBackground": "rgba(234, 92, 0, 0.3)",
  "--theia-peekViewEditor-matchHighlightBackground": "rgba(245, 216, 2, 0.87)",
  "--theia-editorMarkerNavigationError-background": "#e51400",
  "--theia-editorMarkerNavigationError-headerBackground":
    "rgba(229, 20, 0, 0.1)",
  "--theia-editorMarkerNavigationWarning-background": "#bf8803",
  "--theia-editorMarkerNavigationWarning-headerBackground":
    "rgba(191, 136, 3, 0.1)",
  "--theia-editorMarkerNavigationInfo-background": "#1a85ff",
  "--theia-editorMarkerNavigationInfo-headerBackground":
    "rgba(26, 133, 255, 0.1)",
  "--theia-editorMarkerNavigation-background": "#18181b",
  "--theia-editor-foldBackground": "rgba(173, 214, 255, 0.3)",
  "--theia-editorGutter-foldingControlForeground": "#424242",
  "--theia-editorSuggestWidget-background": "#f3f3f3",
  "--theia-editorSuggestWidget-border": "#c8c8c8",
  "--theia-editorSuggestWidget-foreground": "#000000",
  "--theia-editorSuggestWidget-selectedForeground": "#18181b",
  "--theia-editorSuggestWidget-selectedIconForeground": "#18181b",
  "--theia-editorSuggestWidget-selectedBackground": "#0060c0",
  "--theia-editorSuggestWidget-highlightForeground": "#0066bf",
  "--theia-editorSuggestWidget-focusHighlightForeground": "#bbe7ff",
  "--theia-editorSuggestWidgetStatus-foreground": "rgba(0, 0, 0, 0.5)",
  "--theia-editor-linkedEditingBackground": "rgba(255, 0, 0, 0.3)",
  "--theia-editor-wordHighlightBackground": "rgba(87, 87, 87, 0.25)",
  "--theia-editor-wordHighlightStrongBackground": "rgba(14, 99, 156, 0.25)",
  "--theia-editor-wordHighlightTextBackground": "rgba(87, 87, 87, 0.25)",
  "--theia-editorOverviewRuler-wordHighlightForeground":
    "rgba(160, 160, 160, 0.8)",
  "--theia-editorOverviewRuler-wordHighlightStrongForeground":
    "rgba(192, 160, 192, 0.8)",
  "--theia-editorOverviewRuler-wordHighlightTextForeground":
    "rgba(160, 160, 160, 0.8)",
  "--theia-editorHoverWidget-highlightForeground": "#0066bf",
  "--theia-sash-activeBorder": "#0090f1",
  "--theia-activityBar-background": "#ececec",
  "--theia-activityBar-foreground": "#000000",
  "--theia-activityBar-inactiveForeground": "rgba(0, 0, 0, 0.4)",
  "--theia-activityBar-activeBorder": "#000000",
  "--theia-activityBar-dropBackground": "rgba(255, 255, 255, 0.12)",
  "--theia-activityBarBadge-background": "#007acc",
  "--theia-activityBarBadge-foreground": "#18181b",
  "--theia-sideBar-background": "#f3f3f3",
  "--theia-sideBarSectionHeader-background": "rgba(0, 0, 0, 0)",
  "--theia-sideBarSectionHeader-border": "rgba(97, 97, 97, 0.19)",
  "--theia-editorGroup-border": "#e7e7e7",
  "--theia-editorGroup-dropBackground": "rgba(38, 119, 203, 0.18)",
  "--theia-editorGroupHeader-tabsBackground": "#f3f3f3",
  "--theia-tab-activeBackground": "#18181b",
  "--theia-tab-unfocusedActiveBackground": "#18181b",
  "--theia-tab-inactiveBackground": "#ececec",
  "--theia-tab-activeForeground": "#333333",
  "--theia-tab-inactiveForeground": "rgba(51, 51, 51, 0.7)",
  "--theia-tab-unfocusedActiveForeground": "rgba(51, 51, 51, 0.7)",
  "--theia-tab-unfocusedInactiveForeground": "rgba(51, 51, 51, 0.35)",
  "--theia-tab-border": "#f3f3f3",
  "--theia-tab-activeModifiedBorder": "#33aaee",
  "--theia-tab-inactiveModifiedBorder": "rgba(51, 170, 238, 0.5)",
  "--theia-tab-unfocusedActiveModifiedBorder": "rgba(51, 170, 238, 0.7)",
  "--theia-tab-unfocusedInactiveModifiedBorder": "rgba(51, 170, 238, 0.25)",
  "--theia-statusBar-foreground": "#18181b",
  "--theia-statusBar-background": "#007acc",
  "--theia-statusBar-noFolderForeground": "#18181b",
  "--theia-statusBar-noFolderBackground": "#68217a",
  "--theia-statusBarItem-activeBackground": "rgba(255, 255, 255, 0.18)",
  "--theia-statusBarItem-hoverBackground": "rgba(255, 255, 255, 0.12)",
  "--theia-statusBarItem-errorBackground": "#c72e0f",
  "--theia-statusBarItem-errorForeground": "#CFFAFE",
  "--theia-statusBarItem-warningBackground": "#725102",
  "--theia-statusBarItem-warningForeground": "#18181b",
  "--theia-panel-background": "#18181b",
  "--theia-panel-border": "#18181b",
  "--theia-panel-dropBackground": "#18181b",
  "--theia-panelTitle-activeForeground": "#18181b",
  "--theia-panelTitle-inactiveForeground": "#18181b",
  "--theia-panelTitle-activeBorder": "#18181b",
  "--theia-panelInput-border": "#dddddd",
  "--theia-imagePreview-border": "#18181b",
  "--theia-titleBar-activeForeground": "#333333",
  "--theia-titleBar-inactiveForeground": "rgba(51, 51, 51, 0.6)",
  "--theia-titleBar-activeBackground": "#dddddd",
  "--theia-titleBar-inactiveBackground": "rgba(221, 221, 221, 0.6)",
  "--theia-menubar-selectionForeground": "#333333",
  "--theia-menubar-selectionBackground": "rgba(184, 184, 184, 0.31)",
  "--theia-welcomePage-buttonBackground": "rgba(0, 0, 0, 0.04)",
  "--theia-welcomePage-buttonHoverBackground": "rgba(0, 0, 0, 0.1)",
  "--theia-walkThrough-embeddedEditorBackground": "#f4f4f4",
  "--theia-settings-headerForeground": "#444444",
  "--theia-settings-modifiedItemIndicator": "#66afe0",
  "--theia-settings-dropdownBackground": "#18181b",
  "--theia-settings-dropdownForeground": "#616161",
  "--theia-settings-dropdownBorder": "#cecece",
  "--theia-settings-dropdownListBorder": "#c8c8c8",
  "--theia-settings-checkboxBackground": "#18181b",
  "--theia-settings-checkboxForeground": "#616161",
  "--theia-settings-checkboxBorder": "#cecece",
  "--theia-settings-textInputBackground": "#18181b",
  "--theia-settings-textInputForeground": "rgba(250, 250, 250, 0.8)",
  "--theia-settings-textInputBorder": "#cecece",
  "--theia-settings-numberInputBackground": "#18181b",
  "--theia-settings-numberInputForeground": "#616161",
  "--theia-settings-numberInputBorder": "#cecece",
  "--theia-settings-focusedRowBackground": "rgba(128, 128, 128, 0.03)",
  "--theia-settings-rowHoverBackground": "rgba(128, 128, 128, 0.05)",
  "--theia-settings-focusedRowBorder": "rgba(0, 0, 0, 0.12)",
  "--theia-variable-name-color": "#9b46b0",
  "--theia-variable-value-color": "rgba(108, 108, 108, 0.8)",
  "--theia-variable-number-variable-color": "#09885a",
  "--theia-variable-boolean-variable-color": "#0000ff",
  "--theia-variable-string-variable-color": "#a31515",
  "--theia-ansi-black-color": "#808080",
  "--theia-ansi-red-color": "#be1717",
  "--theia-ansi-green-color": "#338a2f",
  "--theia-ansi-yellow-color": "#beb817",
  "--theia-ansi-blue-color": "#00008b",
  "--theia-ansi-magenta-color": "#8b008b",
  "--theia-ansi-cyan-color": "#008b8b",
  "--theia-ansi-white-color": "#bdbdbd",
  "--theia-errorBackground": "#f2dede",
  "--theia-successBackground": "#48985d",
  "--theia-warningBackground": "#bf8803",
  "--theia-warningForeground": "#f6f5d2",
  "--theia-statusBar-offlineBackground": "#bf8803",
  "--theia-statusBar-offlineForeground": "#18181b",
  "--theia-statusBarItem-offlineHoverBackground": "#fbb614",
  "--theia-statusBarItem-offlineActiveBackground": "#fcc23a",
  "--theia-statusBarItem-remoteBackground": "#16825d",
  "--theia-statusBarItem-remoteForeground": "#18181b",
  "--theia-secondaryButton-foreground": "rgba(66, 66, 71, 0.8)",
  "--theia-secondaryButton-disabledForeground": "rgba(97, 97, 97, 0.5)",
  "--theia-secondaryButton-background": "#18181b",
  "--theia-secondaryButton-hoverBackground": "#18181b",
  "--theia-secondaryButton-disabledBackground": "rgba(255, 255, 255, 0.6)",
  "--theia-button-disabledForeground": "rgba(255, 255, 255, 0.5)",
  "--theia-button-disabledBackground": "rgba(0, 122, 204, 0.5)",
  "--theia-editorGutter-commentRangeForeground": "#c5c5c5",
  "--theia-mainToolbar-background": "#18181b",
  "--theia-mainToolbar-foreground": "#18181b",
  "--theia-editorHoverWidgetInternalBorder": "rgba(200, 200, 200, 0.5)",
  "--theia-notifications-foreground": "#616161",
  "--theia-notifications-background": "#f3f3f3",
  "--theia-notificationLink-foreground": "#006ab1",
  "--theia-notificationCenterHeader-background": "#e7e7e7",
  "--theia-notifications-border": "#e7e7e7",
  "--theia-notificationsErrorIcon-foreground": "#e51400",
  "--theia-notificationsWarningIcon-foreground": "#bf8803",
  "--theia-notificationsInfoIcon-foreground": "#1a85ff",
  "--theia-terminal-background": "#18181b",
  "--theia-terminal-foreground": "#333333",
  "--theia-terminal-selectionBackground": "#add6ff",
  "--theia-terminal-inactiveSelectionBackground": "rgba(173, 214, 255, 0.5)",
  "--theia-terminal-border": "#18181b",
  "--theia-terminal-ansiBlack": "#000000",
  "--theia-terminal-ansiRed": "#cd3131",
  "--theia-terminal-ansiGreen": "#00bc00",
  "--theia-terminal-ansiYellow": "#949800",
  "--theia-terminal-ansiBlue": "#0451a5",
  "--theia-terminal-ansiMagenta": "#bc05bc",
  "--theia-terminal-ansiCyan": "#0598bc",
  "--theia-terminal-ansiWhite": "#555555",
  "--theia-terminal-ansiBrightBlack": "#666666",
  "--theia-terminal-ansiBrightRed": "#cd3131",
  "--theia-terminal-ansiBrightGreen": "#14ce14",
  "--theia-terminal-ansiBrightYellow": "#b5ba00",
  "--theia-terminal-ansiBrightBlue": "#0451a5",
  "--theia-terminal-ansiBrightMagenta": "#bc05bc",
  "--theia-terminal-ansiBrightCyan": "#0598bc",
  "--theia-terminal-ansiBrightWhite": "#a5a5a5",
  "--theia-editor-stackFrameHighlightBackground": "rgba(255, 255, 102, 0.45)",
  "--theia-editor-focusedStackFrameHighlightBackground":
    "rgba(206, 231, 206, 0.45)",
  "--theia-statusBar-debuggingBackground": "#cc6633",
  "--theia-statusBar-debuggingForeground": "#18181b",
  "--theia-debugExceptionWidget-border": "#a31515",
  "--theia-debugExceptionWidget-background": "#f1dfde",
  "--theia-debugIcon-breakpointForeground": "#e51400",
  "--theia-debugIcon-breakpointDisabledForeground": "#848484",
  "--theia-debugIcon-breakpointUnverifiedForeground": "#848484",
  "--theia-debugIcon-breakpointCurrentStackframeForeground": "#be8700",
  "--theia-debugIcon-breakpointStackframeForeground": "#89d185",
  "--theia-debugIcon-startForeground": "#388a34",
  "--theia-debugIcon-pauseForeground": "#007acc",
  "--theia-debugIcon-stopForeground": "#a1260d",
  "--theia-debugIcon-disconnectForeground": "#a1260d",
  "--theia-debugIcon-restartForeground": "#388a34",
  "--theia-debugIcon-stepOverForeground": "#007acc",
  "--theia-debugIcon-stepIntoForeground": "#007acc",
  "--theia-debugIcon-stepOutForeground": "#007acc",
  "--theia-debugIcon-continueForeground": "#007acc",
  "--theia-debugIcon-stepBackForeground": "#007acc",
  "--theia-debugConsole-infoForeground": "#1a85ff",
  "--theia-debugConsole-warningForeground": "#bf8803",
  "--theia-debugConsole-errorForeground": "#a1260d",
  "--theia-debugConsole-sourceForeground": "#616161",
  "--theia-debugConsoleInputIcon-foreground": "#616161",
  "--theia-notebook-cellBorderColor": "#e8e8e8",
  "--theia-notebook-focusedEditorBorder": "#0090f1",
  "--theia-notebookStatusSuccessIcon-foreground": "#388a34",
  "--theia-notebookEditorOverviewRuler-runningCellForeground": "#388a34",
  "--theia-notebookStatusErrorIcon-foreground": "#a1260d",
  "--theia-notebookStatusRunningIcon-foreground": "#616161",
  "--theia-notebook-cellToolbarSeparator": "#18181b",
  "--theia-notebook-selectedCellBackground": "rgba(200, 221, 241, 0.31)",
  "--theia-notebook-selectedCellBorder": "#e8e8e8",
  "--theia-notebook-focusedCellBorder": "#0090f1",
  "--theia-notebook-inactiveFocusedCellBorder": "#e8e8e8",
  "--theia-notebook-cellStatusBarItemHoverBackground":
    "rgba(255, 255, 255, 0.15)",
  "--theia-notebook-cellInsertionIndicator": "#0090f1",
  "--theia-notebookScrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
  "--theia-notebookScrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--theia-notebookScrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
  "--theia-notebook-symbolHighlightBackground": "rgba(253, 255, 0, 0.2)",
  "--theia-notebook-cellEditorBackground": "#f3f3f3",
  "--theia-editorGutter-modifiedBackground": "#2090d3",
  "--theia-editorGutter-addedBackground": "#48985d",
  "--theia-editorGutter-deletedBackground": "#e51400",
  "--theia-minimapGutter-modifiedBackground": "#2090d3",
  "--theia-minimapGutter-addedBackground": "#48985d",
  "--theia-minimapGutter-deletedBackground": "#e51400",
  "--theia-editorOverviewRuler-modifiedForeground": "rgba(32, 144, 211, 0.6)",
  "--theia-editorOverviewRuler-addedForeground": "rgba(72, 152, 93, 0.6)",
  "--theia-editorOverviewRuler-deletedForeground": "rgba(229, 20, 0, 0.6)",
  "--theia-extensionButton-prominentBackground": "#327e36",
  "--theia-extensionButton-prominentForeground": "#18181b",
  "--theia-extensionButton-prominentHoverBackground": "#28632b",
  "--theia-extensionEditor-tableHeadBorder": "rgba(0, 0, 0, 0.7)",
  "--theia-extensionEditor-tableCellBorder": "rgba(0, 0, 0, 0.2)",
  "--theia-extensionIcon-verifiedForeground": "#40a6ff",
};
